name: Endocrine Daily Tweets

on:
  schedule:
    # 09:00 İstanbul = 06:00 UTC
    - cron: "0 6 * * *"
    # 15:00 İstanbul = 12:00 UTC
    - cron: "0 12 * * *"
    # 21:00 İstanbul = 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch: # Manuel tetikleme

jobs:
  run-daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DRY_RUN: "0"             # test için 1, gerçek tweet için 0
          TWEETS_PER_DAY: "1"      # her çalıştırmada 1 tweet atsın
          LOOKBACK_DAYS: "90"
          MAX_CANDIDATES: "10"
        run: python app.py
